config/routes.rb
Blackjack::Application.routes.draw do
  resources :user_games

  resources :cards

  resources :games do
 		collection do
    	get 'setup'
			get 'play'
			get 'hit'
			get 'stand'
  	end
	end

  resources :users do
		collection do
			get 'logout'
		end
	end

  resources :credentials

	root :to => 'users#welcome'

end

app/models/user_game.rb
# alias Hand:  joins User and Game and has cards
class UserGame < ActiveRecord::Base 
  belongs_to :user
  belongs_to :game
	has_many	 :cards

	after_create do
	 	cards << Card.hit
		cards << Card.hit
	end

	# default ace value is 1.  When is it 11? Review the rules.
	# depends on who holds the hand:  dealer or player
	def value # value of the hand
		non_aces = cards.find_all { |c| c.rank != "ace" }
		aces = cards.find_all { |c| c.rank == "ace" }
		non_aces_value = non_aces.reduce(0) { |m,c| m + c.value }
		
		retval, boundary = non_aces_value, 21 - non_aces_value
		if !aces.empty? then
			retval += aces.count
			if aces.count <= boundary then
				# assert: 1 to 4 aces. to gain understand, do case analysis on aces.count
				# assert: at most one of the aces can have the value 1
				retval += (11 <= boundary) ? 10 : 0
			end
		end

		retval
	end # method value

	def busted?
		value > 21
	end
end

app/controllers/user_games_controller.rb
class UserGamesController < ApplicationController
  # GET /user_games
  # GET /user_games.json
  def index
    @user_games = UserGame.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_games }
    end
  end

  # GET /user_games/1
  # GET /user_games/1.json
  def show
    @user_game = UserGame.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_game }
    end
  end

  # GET /user_games/new
  # GET /user_games/new.json
  def new
    @user_game = UserGame.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_game }
    end
  end

  # GET /user_games/1/edit
  def edit
    @user_game = UserGame.find(params[:id])
  end

  # POST /user_games
  # POST /user_games.json
  def create
    @user_game = UserGame.new(params[:user_game])

    respond_to do |format|
      if @user_game.save
        format.html { redirect_to @user_game, notice: 'User game was successfully created.' }
        format.json { render json: @user_game, status: :created, location: @user_game }
      else
        format.html { render action: "new" }
        format.json { render json: @user_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_games/1
  # PUT /user_games/1.json
  def update
    @user_game = UserGame.find(params[:id])

    respond_to do |format|
      if @user_game.update_attributes(params[:user_game])
        format.html { redirect_to @user_game, notice: 'User game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_games/1
  # DELETE /user_games/1.json
  def destroy
    @user_game = UserGame.find(params[:id])
    @user_game.destroy

    respond_to do |format|
      format.html { redirect_to user_games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_games_helper.rb
module UserGamesHelper
end

app/views/user_games/_form.html.erb
<%= simple_form_for(@user_game) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :game %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_games/edit.html.erb
<h1>Editing user_game</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_game %> |
<%= link_to 'Back', user_games_path %>

app/views/user_games/index.html.erb
<h1>Listing user_games</h1>

<table>
  <tr>
    <th>User</th>
    <th>Game</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_games.each do |user_game| %>
  <tr>
    <td><%= user_game.user %></td>
    <td><%= user_game.game %></td>
    <td><%= link_to 'Show', user_game %></td>
    <td><%= link_to 'Edit', edit_user_game_path(user_game) %></td>
    <td><%= link_to 'Destroy', user_game, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User game', new_user_game_path %>

app/views/user_games/new.html.erb
<h1>New user_game</h1>

<%= render 'form' %>

<%= link_to 'Back', user_games_path %>

app/views/user_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_game.user %>
</p>

<p>
  <b>Game:</b>
  <%= @user_game.game %>
</p>


<%= link_to 'Edit', edit_user_game_path(@user_game) %> |
<%= link_to 'Back', user_games_path %>