config/routes.rb
Blackjack::Application.routes.draw do
  resources :user_games

  resources :cards

  resources :games do
 		collection do
    	get 'setup'
			get 'play'
			get 'hit'
			get 'stand'
  	end
	end

  resources :users do
		collection do
			get 'logout'
		end
	end

  resources :credentials

	root :to => 'users#welcome'

end

app/models/card.rb
class Card < ActiveRecord::Base 
  belongs_to :user_game

	@@numbers = (2..10).to_a.map { |i| i.to_s }
	@@royalty = [ "jack", "queen", "king" ]
	@@ranks = [ "ace" ] + @@numbers + @@royalty

	# legal values for the rank attribute
	def self.ranks
		@@ranks
	end

	# evaluator. works correctly for all but aces
	# pending:  ace defaults to 1. When is it 11?
	def self.values
		Hash[
			[[ "ace", 1 ]] + 
			@@numbers.map { |si| [ si, si.to_i ] } + 
			@@royalty.map { |royal| [ royal, 10 ] }
		]
	end

	def self.hit # simulates getting a random card from the deck
		# generate a random number between 0 and 12
		# use it to index into the collection of all ranks
		# return a card with that rank
		self.create( :rank => self.ranks[ rand( 12)])
	end

	# value of this card. for the ace, depends on whose hand it is in:  dealer or player
	def value 
		self.class.values[self.rank]
	end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for(@card) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :rank %>
    <%= f.input :suit %>
    <%= f.association :user_game %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <tr>
    <th>Rank</th>
    <th>Suit</th>
    <th>User game</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cards.each do |card| %>
  <tr>
    <td><%= card.rank %></td>
    <td><%= card.suit %></td>
    <td><%= card.user_game %></td>
    <td><%= link_to 'Show', card %></td>
    <td><%= link_to 'Edit', edit_card_path(card) %></td>
    <td><%= link_to 'Destroy', card, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rank:</b>
  <%= @card.rank %>
</p>

<p>
  <b>Suit:</b>
  <%= @card.suit %>
</p>

<p>
  <b>User game:</b>
  <%= @card.user_game %>
</p>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>